name = "Newb X Floren"
version = [0, 2, 1]
min_supported_mc_version = [1, 21, 20]
description = '''
ยงc%w
ยง7- Make your Minecraft better!
%v
ยง3https://devendrn.github.io/newb-shader/
''' # %w = patch warning, %v = version
authors = ["congchu", "devendrn"]
url = "https://devendrn.github.io/newb-shader/"
uuid = "87fe3a36-f221-4cc8-9aa0-1b3fb725ea86" # Use https://www.uuidgenerator.net/version4
materials = ["Sky", "RenderChunk", "Actor", "LegacyCubemap", "EndSky", "Clouds", "SunMoon", "Weather"]

[info] 
copyright = '''
Copyright (c) %a

**Important Note:** Redistribution of this resource pack with links other than the official ones provided by the creator is strictly prohibited.
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default

[[subpack]]
define = "EXTRA_MULTILAYER_CLOUDS"
materials = ["Clouds"]
description = '''
Extra Multilayer Clouds
'''

[[subpack]]
define = "ENCHANTED_EFFECTS"
materials = ["ActorGlint", "ItemInHandColor", "ItemInHandColorGlint", "ItemInHandTextured", "Stars"]
description = '''
Enchanted Effects
'''

[[subpack]]
define = "DEFAULT"
materials = []
description = '''
Default
'''
