name: build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  windows:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-win-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        .\build.bat setup
        .\build.bat pack -p windows --no-zip
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-windows
        path: ./build/pack-windows
  android:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-linux-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        ./build.sh setup
        ./build.sh pack -p android --no-zip
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-android
        path: ./build/pack-android
  ios:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-linux-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        wget https://github.com/mcbegamerxx954/material-updater/releases/download/v0.1.11-hotfix2/material-updater-x86_64-unknown-linux-gnu.tar.gz
        tar xvzf material-updater-x86_64-unknown-linux-gnu.tar.gz
    - run: |
        ./build.sh setup
        ./build.sh pack -p ios
        ./material-updater -t v1.21.20 -o ./build/nxf-ios.zip ./build/pack-ios.zip
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-ios
        path: ./build/nxf-ios.zip
  merged:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
        cache: 'pip'
    - uses: actions/cache@v4
      with:
        key: env-files-win-laz
        path: |
          ${{ github.workspace }}/tool/data
    - run: pip install -r requirements.txt
    - run: |
        .\build.bat setup
        .\build.bat pack -p merged --no-zip
    - uses: actions/upload-artifact@v4
      with:
        name: newb-x-merged
        path: ./build/pack-merged
